# Using the container-based Ubuntu 14.04 Trusty setup
language: shell
script:
  - cd .
  - latexmk -pdf -f -latexoption="--interaction=nonstopmode" ssh.tex
after_success:
  - mv ssh.pdf vortrag_ssh.pdf
deploy:
  skip_cleanup: true
  provider: script
  script: wget https://raw.githubusercontent.com/foss-ag/script_deploy-artifact/master/deploy-artifact.sh ; sh deploy-artifact.sh *.pdf
  on:
    all_branches: true
addons:
  apt:
    packages: [texlive, latexmk, latex-beamer, texlive-lang-german, texlive-latex-extra]
